### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by leopard-aqi** [weizhou-geek/NR-LFQA#1]
您好，非常感谢您提供的代码，我做实验时输入的是5DLF（9,9,434,625,3）的矩阵，但看到您main方程里输入的是HEVC_Bikes_44.bmp，所以请问可以提供一张这样的图片吗

**Comment by weizhou-geek** [comment]
You can find the image in https://drive.google.com/open?id=1cipAqfAqJp8f1Paq4Hj4BaHMKyjzt0PN

**Comment by weizhou-geek** [comment]
> 您好，非常感谢您提供的代码，我做实验时输入的是5DLF（9,9,434,625,3）的矩阵，但看到您main方程里输入的是HEVC_Bikes_44.bmp，所以请问可以提供一张这样的图片吗

The image can be found in https://drive.google.com/open?id=1cipAqfAqJp8f1Paq4Hj4BaHMKyjzt0PN

**Comment by leopard-aqi** [comment]
好的，感谢(❁´ω`❁)


 
---原始邮件---
发件人: "Wei Zhou"<notifications@github.com&gt;
发送时间: 2019年12月6日(星期五) 下午2:32
收件人: "weizhou-geek/NR-LFQA"<NR-LFQA@noreply.github.com&gt;;
抄送: "leopard-aqi"<1352472904@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题: Re: [weizhou-geek/NR-LFQA] 请教 (#1)


 
您好，非常感谢您提供的代码，我做实验时输入的是5DLF（9,9,434,625,3）的矩阵，但看到您main方程里输入的是HEVC_Bikes_44.bmp，所以请问可以提供一张这样的图片吗
  
You can find the image in https://drive.google.com/open?id=1cipAqfAqJp8f1Paq4Hj4BaHMKyjzt0PN
